### ISSUE TITLE
Break code into multiple files

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/recipe-box#38]
#2

**Comment by atherdon** [comment]
@RAJAGOPALAN-GANGADHARAN Please start from this task. because it's a first item in our plan.
Feel free to ask your questions

**Comment by atherdon** [comment]
not a problem. maybe it's split into a parts, but does that parts works?


On 19-Jun-2018 at 04:30 AM, RAJAGOPALAN-GANGADHARAN wrote:


@atherdon <https://github.com/atherdon> but its already broken down into
pieces right.Where am i supposed to break it even more.Sorry if this
question is so stupid 😕

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/recipe-box/issues/38#issuecomment-398271041>,
or mute the thread

**Comment by atherdon** [comment]
@RAJAGOPALAN-GANGADHARAN tell me if you need help or have questions to me

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@atherdon I wont be able to work on this right now will start as soon as i get home.Thank you 😄
