### ISSUE TITLE
not sure if we're using the latest react-scripts

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/recipe-box#5]
please check it and upgrade if necessary

**Comment by AlexErling** [comment]
Hi, I am new to open source and interested in helping. Can I take this on? This seems pretty explanatory but anything I need to look out for?

**Comment by atherdon** [comment]
@AlexErling are you want to participate into this project or maybe you want to know more about what we're doing?

**Comment by atherdon** [comment]
#6
